name: Feature Request
description: Suggest an idea
labels: [feature]
title: 'Feature / '
body:
  - type: textarea
    id: description
    attributes:
      description: 기능에 대해서 설명해주세요.
      label: Description
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: solution
    attributes:
      label: Solution
      placeholder: 어떻게 구현할 수 있을지 설명해주세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: etc
    attributes:
      description: 참고자료 등 기타 정보가 있다면 적어주세요.
      label: etc.
    validations:
      required: false