name: Bug Report
description: Report a bug
labels: [bug]
title: 'Bug / '
body:
  - type: textarea
    id: description
    attributes:
      description: 버그에 대해서 설명해주세요. 재현 방법 등 자세히 알려주세요.
      label: Bug description
      value: |
        


        ---
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      placeholder: 어떻게 해결할 수 있을지 설명해주세요.
      value: |


        ---
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: 참고자료 등 기타 정보가 있다면 적어주세요.
    validations:
      required: false