name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.6.1'

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm typecheck

      - name: Build packages
        run: pnpm build

      - name: Setup npm authentication
        run: |
          echo "@redotlabs:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.REDOT_PAT }}" >> ~/.npmrc
          echo "Current .npmrc contents:"
          cat ~/.npmrc

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.REDOT_PAT }}
          NPM_TOKEN: ${{ secrets.REDOT_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.REDOT_PAT }}