name: Deploy Storybook

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Push to deploy repository
        run: git push --force https://redot-dev:${{ secrets.REDOT_PRIVATE_PAT }}@github.com/redot-dev/design-system-deploy.git main
