name: Deploy Storybook

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  deploy:
    if: github.repository == 'redotlabs/design-system'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REDOT_PRIVATE_PAT }}
          fetch-depth: 0 

      - name: Push to deploy repository
        run: |
          git remote add deploy https://redot-dev:${{ secrets.REDOT_PRIVATE_PAT }}@github.com/redot-dev/design-system-deploy.git
          git push --force deploy main
